GET https://gocardless.com/api/v1/merchants/{MERCHANT_ID} HTTP/1.1

HTTP/1.1 200 OK
{
  "created_at": "2011-11-18T17:07:09Z",
  "description": "Payments for monthly magazine subscriptions",
  "id": "MERCHANT_ID",
  "name": "Tom's Magazine",
  "first_name": "Tom",
  "last_name": "Blomfield",
  "email": "help@gocardless.com",
  "uri": "https://gocardless.com/api/v1/merchants/MERCHANT_ID",
  "balance": "12.00",
  "pending_balance": "20.00",
  "next_payout_date": "2014-08-01",
  "next_payout_amount": "12.00",
  "hide_variable_amount": true,
  "sub_resource_uris": {
    "users": "https://gocardless.com/api/v1/merchants/MERCHANT_ID/users",
    "bills": "https://gocardless.com/api/v1/merchants/MERCHANT_ID/bills",
    "pre_authorizations": "https://gocardless.com/api/v1/merchants/MERCHANT_ID/pre_authorizations",
    "subscriptions": "https://gocardless.com/api/v1/merchants/MERCHANT_ID/subscriptions",
    "payouts": "https://gocardless.com/api/v1/merchants/MERCHANT_ID/payouts"
  }
}
