GET https://gocardless.com/connect/subscriptions/new?client_id=123ABC&timestamp=2014-06-10T08%3A42%3A22Z&nonce=ABCDEF123%3D&subscription[amount]=10.00&subscription[interval_length]=1&subscription[interval_unit]=month&subscription[merchant_id]=06Z06JWQW1&signature=11abc2d3e1 HTTP/1.1
