GET https://gocardless.com/connect/pre_authorizations/new?client_id=123ABC&timestamp=2014-06-10T08%3A42%3A22Z&nonce=ABCDEF123%3D&pre_authorization[amount]=10.00&pre_authorization[interval_length]=1&pre_authorization[interval_unit]=month&pre_authorization[max_amount]=1000.00&pre_authorization[merchant_id]=06Z06JWQW1&signature=11abc2d3e1 HTTP/1.1
