GET https://sandbox.gocardless.com/connect/subscriptions/new?client_id=123ABC&timestamp=2013-11-22T15%3A04%3A17.135Z&nonce=ABCDEF123%3D&pre_authorization[amount]=10.00&pre_authorization[interval_length]=1&pre_authorization[interval_unit]=month&pre_authorization[merchant_id]=06Z06JWQW1&signature=11abc2d3e1 HTTP/1.1
