PUT https://gocardless.com/api/v1/bills/{BILL_ID}/cancel HTTP/1.1

HTTP/1.1 200 OK
{
  "amount": "44.0",
  "gocardless_fees": "0.44",
  "amount_minus_fees": "43.56",
  "partner_fees": "0.0",
  "currency": "GBP",
  "created_at": "2014-05-12T16:06:54Z",
  "description": "Bill description",
  "id": "0P1AVA0D6A",
  "name": "Bill name",
  "paid_at":  null,
  "status": "cancelled",
  "merchant_id": "0A1B2C3D4E",
  "user_id": "4A3B2C1D0E",
  "source_type": "ad_hoc_authorization",
  "source_id": "0B1B2B3B4B",
  "uri": "https://gocardless.com/api/v1/bills/0P1AVA0D6A",
  "can_be_retried": false,
  "can_be_cancelled": false,
  "payout_id": null,
  "is_setup_fee": false,
  "charge_customer_at": "2014-05-27"
}